### PR TITLE
Provide support for Jekyll 3

### PR DESCRIPTION
**Pull request by gjtorikian**
Closes https://github.com/benbalter/jekyll-auth/issues/63

I uhhhh opened this in September but didn't submit this. Why?

### CODE REVIEW

**Comment by gjtorikian** [comment]
@benbalter Just a head's up that the branch now has some trickery for 1.9.3, since Jekyll 3.x only supports Ruby 2 and higher. 

Ruby 1.9.3 [was end-of-lifed](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) earlier this year. I assume if you wanted to :skull: Ruby 1.9.3 you'd need a new major version of this gem. 

At any rate a bump + release for Jekyll 3 would be much obliged. :pray:

**Comment by benbalter** [comment]
Thanks @gjtorikian. I may drop Jekyll < 3 support to minimize the maintenance burden. https://github.com/benbalter/jekyll-auth/pull/71 is going to require a major bump anyway.

**Comment by benbalter** [comment]
>  I may drop Jekyll < 3 support to minimize the maintenance burden. 

And by Jekyll < 3, of course, I mean Ruby 1.9.3.

**Comment by benbalter** [comment]
> At any rate a bump + release for Jekyll 3 would be much obliged.

https://github.com/benbalter/jekyll-auth/releases/tag/v2.0.0

**Comment by gjtorikian** [comment]
:metal:

**Pull request merged**
