### PR TITLE
changed all refs from org_id to org_team

### PR DESCRIPTION
**Pull request by jarrodparkes**
@benbalter 

First attempt at contributing to an open source project, so apologies if I am doing something incorrect. Also, I was unsure how to test the changes since I am not a ruby developer (`rake test`?). 

Best,
Jarrod

### CODE REVIEW

**Comment by jarrodparkes** [comment]
@benbalter 

Just checking up. It seems like the Travis CI tests passed (I didn't even know what that was, how cool!).

How do things look on your end?

Best,
Jarrod

**Comment by jarrodparkes** [comment]
@benbalter 

Any updates?

**Comment by benbalter** [comment]
@jarrodparkes Makes sense. Sorry this slipped past me.

**Comment by benbalter** [comment]
Thanks for the patience and for taking the time to put the pull request together.

**Pull request merged**
